### ISSUE TITLE
USER STORY: Site Contact Information

### ISSUE THREAD

**Issue by gbroder24** [gbroder24/django-the-failte-bistro#14]
As a user I can visit the bistro website so that I can view their contact information

## Acceptance Criteria:

* Acceptance criteria 1 - A user can view a phone number.

* Acceptance criteria 2 - A user can view an email address.

* Acceptance criteria 3 - A user can view an address.

## Tasks:

- [ ] Add a phone number.
    
- [ ] Add email address.

- [ ] Add a street address.
