### ISSUE TITLE
USER STORY:  Navigation Bar

### ISSUE THREAD

**Issue by gbroder24** [gbroder24/django-the-failte-bistro#18]
As a user I can easily navigate the website so that I can find out more information about the bistro.

## Acceptance Criteria:

* Acceptance criteria 1 - User can navigate to the Home page.

* Acceptance criteria 2 - User can navigate to the About page.

* Acceptance criteria 3 - User can navigate to the Menu page.

* Acceptance criteria 4 - User can navigate to the Signup page.

* Acceptance criteria 5 - User can navigate to the Login page.

* Acceptance criteria 6 - User can navigate to the Signup / Login page via the Booking link.

## Tasks:

- [ ] Add a Home link to the navigation bar.
    
- [ ] Add a About link to the navigation bar.

- [ ] Add a Menu link to the navigation bar.

- [ ] Add a Signup link to the navigation bar.
    
- [ ] Add a Login link to the navigation bar.

- [ ] Add a Booking link to the navigation bar so that the user will be directed to the signup / login page.
