### ISSUE TITLE
USER STORY: Menu page

### ISSUE THREAD

**Issue by gbroder24** [gbroder24/django-the-failte-bistro#20]
As a user I can view the menu so that I can decide if their food is appetizing.

## Acceptance Criteria:

* Acceptance criteria 1 - User can view a list of menu items on the menu page.

## Tasks:

- [ ] Create a menu template.
    
- [ ] Add links for all menu items, starters, main and deserts.

- [ ] Add content for all menu items listed.
