### ISSUE TITLE
USER STORY: Signup Page

### ISSUE THREAD

**Issue by gbroder24** [gbroder24/django-the-failte-bistro#21]
As a user I can fill out a signup form so that I can create a personal account.

## Acceptance Criteria:

* Acceptance criteria 1 - User can signup using a form.

* Acceptance criteria 2 - User can choose a username.

* Acceptance criteria 3 - User can choose a password.

* Acceptance criteria 4 - User can provide an email address.

## Tasks:

- [ ] Create a signup template
    
- [ ] Add a crispy form

- [ ] Add a username field

- [ ] Add a password field

- [ ] Add a verify password field

- [ ] Add a email field
