### ISSUE TITLE
USER STORY: Login Page

### ISSUE THREAD

**Issue by gbroder24** [gbroder24/django-the-failte-bistro#22]
As a user I can login to my account so that I can access the booking system.

## Acceptance Criteria:

* Acceptance criteria 1 - User will see the login link when logged out.

* Acceptance criteria 2 - User will be directed to the booking system on successful login.

* Acceptance criteria 3 - User will see the logout link when logged in.

* Acceptance criteria 4 - User is alerted upon successful login.

* Acceptance criteria 5 - User can click on a link to reset password.

## Tasks:

- [ ] Create a login template
    
- [ ] Add a logout link in the navigation bar

- [ ] Direct user to booking system

- [ ] Add successful login alert message

- [ ] Add a link for password reset
