### ISSUE TITLE
USER STORY: Booking System

### ISSUE THREAD

**Issue by gbroder24** [gbroder24/django-the-failte-bistro#24]
As a user I can fill out a form so that I can make multiple bookings.

* Acceptance criteria 1 - User fills out a form to create a booking.

* Acceptance criteria 2 - User can book a table on a certain date and time.

* Acceptance criteria 3 - User can book the number of guests.

* Acceptance criteria 4 - User can view / read the booking.

* Acceptance criteria 5 - User can modify the booking.

* Acceptance criteria 6 - User can delete the booking.

* Acceptance criteria 7 - User can avoid double booking.

* Acceptance criteria 8 - User will be alerted if the booking has been created, updated or deleted.

* Acceptance criteria 9 - User will be alerted if the booking is double booked.

## Tasks:

- [ ] Add a crispy form.

- [ ] Add a customer field.

- [ ] Add a first name field.

- [ ] Add a last name field.
    
- [ ] Add a date field.

- [ ] Add a time field.

- [ ] Add a number of guests field.

- [ ] Add a contact number field.
