### ISSUE TITLE
USER STORY: Create Django Applications

### ISSUE THREAD

**Issue by gbroder24** [gbroder24/django-the-failte-bistro#31]
As a developer I can create applications so that I can develop a project in the django environment.

## Acceptance Criteria:

* Acceptance criteria 1 - All applications to be created in the django environment.

## Tasks:

- [x] Create home app.
    
- [x] Create about app.

- [x] Create menu app.

- [x] Create booking app.
