### ISSUE TITLE
USER STORY: Create URL Patterns

### ISSUE THREAD

**Issue by gbroder24** [gbroder24/django-the-failte-bistro#33]
As a developer I can create URL patterns so that my URL patterns list is routed to views.

## Acceptance Criteria:

* Acceptance criteria 1 - URL patterns are routed to views.

## Tasks:

- [x] Create a home URL.
    
- [x] Create a about URL.

- [x] Create a menu URL.

- [x] Create a booking URL.
