### ISSUE TITLE
USER STORY: Installed Apps

### ISSUE THREAD

**Issue by gbroder24** [gbroder24/django-the-failte-bistro#34]
As a developer I can install my applications so that I can connect them to the project database.

## Acceptance Criteria:

* Acceptance criteria 1 - Add applications to settings installed apps.

## Tasks:

- [x] Add home app.
    
- [x] Add about app.

- [x] Add menu app.

- [x] Add booking app.
