### ISSUE TITLE
USER STORY: Test Application

### ISSUE THREAD

**Issue by gbroder24** [gbroder24/django-the-failte-bistro#35]
As a developer I can test my application so that I know that it is wired up correctly.

## Acceptance Criteria:

* Acceptance criteria 1 - Run the server and verify that you can view the correct content in your browser window.

## Tasks:

- [x] Verify home is wired up correctly.
    
- [x] Verify about is wired up correctly.

- [x] Verify menu is wired up correctly.

- [x] Verify booking is wired up correctly.
