### ISSUE TITLE
USER STORY: Create Wireframe

### ISSUE THREAD

**Issue by gbroder24** [gbroder24/django-the-failte-bistro#36]
As a developer I can create a wire-frame so that I can visualize my project website.

## Acceptance Criteria:

* Acceptance criteria 1 - Create wire-frame to visualize project. 

## Tasks:

- [x] Create a home page wire-frame.
    
- [x] Create a about page wire-frame.

- [x] Create a menu page wire-frame.

- [x] Create a signup page wire-frame.

- [x] Create a login page wire-frame.

- [x] Create a reservations page wire-frame.

- [x] Create a booking page wire-frame.

- [x] Create a password reset page wire-frame.
