### ISSUE TITLE
USER STORY: Create Database Models and Schema

### ISSUE THREAD

**Issue by gbroder24** [gbroder24/django-the-failte-bistro#37]
As a developer I can create database models and schema so that I can create a simplified, logical database and keep data organised.

## Acceptance Criteria:

* Acceptance criteria 1 - Create database models and schema for project.

## Tasks:

- [ ] Create User model.
    
- [ ] Create Reservation model.

- [ ] Create Post model.

- [ ] Create Comment model.

- [ ] Create database schema.
