### ISSUE TITLE
USER STORY: Deploy Project to Heroku

### ISSUE THREAD

**Issue by gbroder24** [gbroder24/django-the-failte-bistro#38]
As a developer I can deploy my project on heroku so that I build and operate it from the cloud.

## Acceptance Criteria:

* Acceptance criteria 1 - Project to be built and operated from a cloud based platform Heroku.

## Tasks:

- [x] Create heroku app.
    
- [x] Update code for deployment.

- [x] Deploy on heroku.
