### ISSUE TITLE
USER STORY: Create PostgreSQL Database

### ISSUE THREAD

**Issue by gbroder24** [gbroder24/django-the-failte-bistro#39]
As a developer I can create a database so that I can store and retrieve data and information.

## Acceptance Criteria:

* Acceptance criteria 1 - Create a database with postgreSQL.

## Tasks:

- [ ] Create postgreSQL instance.
    
- [ ] Connect database to code

- [ ] Enter data into the database

- [ ] Connect Heroku to the PostgreSQL database
